# Tutorial 1: Introduction to GenCoMo

## GENeral-morphology COmpartmental MOdeling

Welcome to GenCoMo! This tutorial introduces you to z-stack based compartmental modeling of neurons. GenCoMo uses a volumetric approach with 3D binary arrays (z-stacks) as the native format for representing neuronal morphologies, enabling accurate modeling of complex geometries from imaging data.

### What you'll learn:
1. Creating neuronal morphologies as z-stack binary arrays
2. Converting morphologies to compartmental models
3. Setting up biophysical simulations
4. Analyzing action potential propagation
5. Working with real imaging data

### Key Concepts:
- **Z-stack morphology**: Binary 3D arrays where 1=inside neuron, 0=outside
- **Volumetric precision**: Accurate representation of complex shapes and topologies
- **Z-axis slicing**: Natural conversion from z-stacks to compartments
- **Graph connectivity**: Build electrical connections between compartments
- **Hodgkin-Huxley dynamics**: Simulate action potentials

### Why Z-stacks?
- **Direct from imaging**: Confocal, 2-photon, EM data → GenCoMo
- **Complex topology**: Handles branching, holes, irregular shapes
- **High precision**: Preserves fine morphological details
- **Natural slicing**: Perfect fit for compartmental modeling

## 1. Import Required Libraries and Setup

First, let's import all the necessary libraries for this tutorial.

In [3]:
# Import core scientific libraries
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import warnings

# Suppress warnings for cleaner output
warnings.filterwarnings('ignore')

# Import GenCoMo package components
import sys
sys.path.append('../')  # Add parent directory to path

# Core GenCoMo modules
from gencomo import (
    Neuron, Compartment, CompartmentGraph,
    MeshProcessor, ZAxisSlicer, RegionDetector, 
    GraphBuilder, ODESystem, Simulator,
    # Z-stack functions (primary format)
    create_cylinder_zstack, create_y_shaped_zstack, create_hole_zstack,
    visualize_zstack_3d, save_zstack_data, load_zstack_data,
    analyze_zstack_properties,
    # Mesh conversion utilities
    load_mesh_file_to_zstack, mesh_to_zstack
)

print("✅ All libraries imported successfully!")
print("📦 GenCoMo version: 0.1.0")
print("🧠 Ready for z-stack based compartmental modeling!")

# Configure plotting
plt.style.use('default')
%matplotlib inline

✅ All libraries imported successfully!
📦 GenCoMo version: 0.1.0
🧠 Ready for z-stack based compartmental modeling!


## 2. Creating Z-stack Morphologies

GenCoMo uses **3D binary arrays (z-stacks)** as its primary format for representing neuronal morphologies. This format directly matches imaging data from confocal microscopy, two-photon imaging, and other 3D acquisition methods.

### Why Z-stacks?

- **Direct imaging integration**: Load reconstructed neurons from imaging pipelines
- **Accurate topology**: Handles complex branching, loops, and connections naturally  
- **Compartmental ready**: Each voxel can become a simulation compartment
- **Format flexibility**: Easy conversion to/from other formats when needed

In [4]:
# Create z-stack morphologies - GenCoMo's native format
print("🧱 Creating z-stack morphologies (native format)...")
print()

# Simple cylindrical morphology
cylinder_zstack, cylinder_meta = create_cylinder_zstack(
    length=20,
    radius=5,
    z_resolution=0.5,
    xy_resolution=0.5
)
print(f"✓ Cylinder z-stack: {cylinder_zstack.shape} voxels")

# Y-shaped branching morphology  
y_zstack, y_meta = create_y_shaped_zstack(
    trunk_length=15,
    trunk_radius=4,
    branch_length=12,
    branch_radius=3,
    branch_angle=45,
    z_resolution=0.5,
    xy_resolution=0.5
)
print(f"✓ Y-branch z-stack: {y_zstack.shape} voxels")

# Complex topology with perpendicular hole (--o--)
hole_zstack, hole_meta = create_hole_zstack(
    length=25,
    outer_radius=6,
    hole_radius=3,
    hole_position=12.5,  # Middle position
    hole_direction="x",  # Creates perpendicular hole
    z_resolution=0.5,
    xy_resolution=0.5
)
print(f"✓ Hole topology z-stack: {hole_zstack.shape} voxels")
print()
print("🎯 Z-stacks ready for visualization and analysis!")

🧱 Creating z-stack morphologies (native format)...

✓ Cylinder z-stack: (48, 28, 28) voxels
✓ Y-branch z-stack: (59, 28, 62) voxels
✓ Hole topology z-stack: (58, 32, 32) voxels

🎯 Z-stacks ready for visualization and analysis!
✓ Y-branch z-stack: (59, 28, 62) voxels
✓ Hole topology z-stack: (58, 32, 32) voxels

🎯 Z-stacks ready for visualization and analysis!


## 3. Visualizing Z-stack Morphologies

GenCoMo provides powerful 3D visualization tools specifically designed for z-stack data. These tools use volume rendering to show the internal structure and topology of neuronal morphologies.

In [ ]:
# Z-stack visualization capabilities
print("🎨 Z-stack visualization tools imported from GenCoMo!")
print("📊 Ready to visualize volumetric neuronal morphologies")
print()
print("Available functions:")
print("  • visualize_zstack_3d() - Interactive 3D volume viewer")
print("  • analyze_zstack_properties() - Morphology analysis")
print("  • create_*_zstack() - Test morphology generators")
print("  • save/load_zstack_data() - File I/O operations")
print()
print("🧱 Z-stack format advantages:")
print("  • Direct representation of imaging data")
print("  • Handles any 3D topology accurately")
print("  • Natural fit for compartmental modeling")
print("  • Preserves fine morphological details")

🎨 3D visualization functions imported from GenCoMo!
📊 Ready to visualize neuronal morphologies

Available functions:
  • visualize_mesh_3d() - Interactive 3D mesh viewer
  • analyze_mesh_properties() - Mesh geometry analysis
  • create_*_mesh() - Test mesh generators


## 4. Analyzing Z-stack Properties

Z-stack morphologies contain rich structural information that can be analyzed for morphometric properties, connectivity patterns, and compartmental modeling preparation.

In [ ]:
# Analyze z-stack morphological properties
print("? Analyzing z-stack morphologies...")
print()

# Analyze each morphology
morphologies = [
    ("Cylinder", cylinder_zstack),
    ("Y-branch", y_zstack), 
    ("Hole topology", hole_zstack)
]

for name, zstack in morphologies:
    props = analyze_zstack_properties(zstack, voxel_size=0.5)
    
    print(f"📊 {name} z-stack analysis:")
    print(f"   • Volume: {props['volume']:.1f} μm³")
    print(f"   • Surface area: {props['surface_area']:.1f} μm²")
    print(f"   • Bounding box: {props['bounding_box']}")
    print(f"   • Connected components: {props['connected_components']}")
    print(f"   • Euler number: {props['euler_number']}")
    print()

print("🎯 Z-stack analysis complete! These properties are essential for:")
print("   • Compartmental model setup")
print("   • Morphology classification") 
print("   • Connectivity analysis")
print("   • Surface-to-volume calculations")

## 5. Z-stack Data Management

GenCoMo provides efficient file I/O operations for z-stack data, enabling easy storage, sharing, and loading of neuronal morphologies in the native format.

In [ ]:
# Z-stack data management - save and load
print("💾 Z-stack file I/O operations...")
print()

# Save z-stack data with metadata
metadata = {
    'morphology_type': 'hole_topology',
    'resolution': 0.5,
    'units': 'micrometers',
    'topology': 'perpendicular_hole',
    'created_with': 'GenCoMo v0.1.0'
}

# Save to compressed .npz format
save_zstack_data(hole_zstack, 'hole_morphology.npz', metadata=metadata)
print("✓ Saved hole topology z-stack to 'hole_morphology.npz'")

# Load z-stack data back
loaded_zstack, loaded_meta = load_zstack_data('hole_morphology.npz')
print(f"✓ Loaded z-stack: {loaded_zstack.shape} voxels")
print(f"✓ Metadata: {loaded_meta}")
print()

# Verify data integrity
data_matches = np.array_equal(hole_zstack, loaded_zstack)
print(f"🔍 Data integrity check: {'✓ PASSED' if data_matches else '✗ FAILED'}")
print()
print("🎯 Z-stack I/O advantages:")
print("   • Compressed storage (.npz format)")
print("   • Preserves exact voxel data")
print("   • Includes metadata for provenance")
print("   • Fast loading for analysis pipelines")

🌳 Visualizing Y-shaped neuron...



📊 Y-shaped Neuron Properties:
  num_vertices: 842
  num_faces: 1680
  volume: None
  surface_area: 3612.2948245286693
  is_watertight: False
  is_winding_consistent: True
  bounds:
    x_range: -30.41 to 30.41 µm
    y_range: -5.00 to 5.00 µm
    z_range: 0.00 to 90.41 µm
  centroid: [-1.2510196478837745e-15, 4.854831554140159e-16, 49.53726047493111]
  bounding_box_volume: 54976.70990922584
  convex_hull_volume: 25285.572431005592

🔍 Notice the branching structure starting at z ≈ 67.8 µm


## 6. Advanced Z-stack Operations

Z-stack morphologies can be processed, filtered, and manipulated using various advanced operations for research and modeling applications.

In [ ]:
# Advanced z-stack processing operations
print("⚙️ Advanced z-stack operations...")
print()

# Cross-sectional analysis
mid_slice = y_zstack.shape[0] // 2
cross_section = y_zstack[mid_slice, :, :]
print(f"✓ Extracted cross-section at z={mid_slice}: {cross_section.shape}")

# Calculate geometric properties
volume_voxels = np.sum(y_zstack)
total_voxels = y_zstack.size
fill_ratio = volume_voxels / total_voxels

print(f"✓ Y-branch fill analysis:")
print(f"   • Volume voxels: {volume_voxels}")
print(f"   • Fill ratio: {fill_ratio:.3f}")
print()

# Morphological operations (future extensions)
print("🔬 Advanced processing capabilities:")
print("   • Cross-sectional analysis")
print("   • Volume fraction calculations")
print("   • Distance transforms")
print("   • Connectivity analysis")
print("   • Surface mesh generation") 
print("   • Compartment segmentation")
print()
print("🎯 These operations prepare z-stacks for:")
print("   • Detailed morphometry")
print("   • Simulation compartmentalization")
print("   • Multi-scale modeling")

🕳️ Visualizing neuron with perpendicular hole...



📊 Neuron with Perpendicular Hole Properties:
  num_vertices: 802
  num_faces: 1600
  volume: 8817.026281691667
  surface_area: 3217.013003210022
  is_watertight: True
  is_winding_consistent: True
  bounds:
    x_range: -6.00 to 6.00 µm
    y_range: -6.00 to 6.00 µm
    z_range: 0.00 to 80.00 µm
  centroid: [-1.7890497035336578e-16, -1.7062233283700623e-16, 40.000000000000135]
  bounding_box_volume: 11520.0
  convex_hull_volume: 8817.026281691667

🔍 The perpendicular hole creates a torus-like topology that represents
    complex neuronal morphologies with branching channels or cavities.
    This topology cannot be modeled with traditional cylinder-based approaches.


## 7. Mesh Conversion Utilities

While z-stacks are GenCoMo's primary format, conversion utilities are available for compatibility with mesh-based workflows and legacy data formats.

In [ ]:
# Mesh conversion utilities (for legacy compatibility)
print("🔄 Z-stack ↔ Mesh conversion utilities...")
print()

# Convert z-stack to mesh (for legacy workflows)
print("Converting z-stack to mesh format...")
mesh_processor = MeshProcessor()

# Note: These are utility functions for compatibility
# Z-stack remains the primary format
try:
    # Generate mesh from z-stack (utility function)
    mesh = mesh_processor.zstack_to_mesh(cylinder_zstack, voxel_size=0.5)
    print(f"✓ Generated mesh: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces")
    
    # Convert back to z-stack (round-trip test)
    roundtrip_zstack = mesh_processor.mesh_to_zstack(
        mesh, 
        resolution=0.5,
        bounds=None  # Auto-detect bounds
    )
    print(f"✓ Round-trip z-stack: {roundtrip_zstack.shape}")
    
except Exception as e:
    print(f"ℹ️ Mesh conversion example (implementation in progress)")
    print(f"   Note: Z-stack format is primary, mesh conversion for compatibility")

print()
print("? Conversion utilities enable:")
print("   • Legacy data import/export")
print("   • Mesh-based visualization tools")
print("   • Cross-platform compatibility")
print("   • Format migration workflows")
print()
print("💡 Recommendation: Use z-stack format for all new work!")

🧱 Z-Stack Binary Array Analysis

Cylinder Z-stack:
  Shape: (53, 16, 16) (z, y, x)
  Resolution: 2.0 µm/slice, 1.0 µm/pixel
  Volume: 6664.0 µm³
  Neuron voxels: 3,332 / 13,568

Y-shaped Z-stack:
  Shape: (50, 20, 77) (z, y, x)
  Resolution: 2.0 µm/slice, 1.0 µm/pixel
  Volume: 5972.0 µm³
  Neuron voxels: 2,986 / 77,000

Hole Z-stack:
  Shape: (43, 18, 18) (z, y, x)
  Resolution: 2.0 µm/slice, 1.0 µm/pixel
  Volume: 7184.0 µm³
  Neuron voxels: 3,592 / 13,932

📊 Sample z-slices from cylinder (middle slice):
Slice 26: 68 neuron pixels
Cross-section:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0]
 [0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 

## 8. Z-stack Workflow Summary

This tutorial demonstrated GenCoMo's z-stack-centered workflow for neuronal morphology analysis and compartmental modeling preparation. The z-stack format provides the most direct path from imaging data to simulation models.

In [ ]:
# Complete z-stack workflow summary
print("🎯 GenCoMo Z-stack Workflow Complete!")
print("=" * 50)
print()
print("✅ What we accomplished:")
print("   1. Created z-stack morphologies (native format)")
print("   2. Visualized 3D structures with volume rendering")
print("   3. Analyzed morphological properties")
print("   4. Managed z-stack data with file I/O")
print("   5. Performed advanced processing operations")
print("   6. Explored mesh conversion utilities")
print()
print("🧠 Z-stack advantages for neuroscience:")
print("   • Direct imaging data integration")
print("   • Accurate complex topology representation")
print("   • Natural compartmental modeling preparation")
print("   • Efficient storage and processing")
print()
print("? Next steps:")
print("   • Load your own imaging data as z-stacks")
print("   • Develop compartmental models from z-stack morphologies")
print("   • Integrate with simulation frameworks")
print("   • Analyze large morphology datasets")
print()
print("📖 Ready to explore compartmental modeling with GenCoMo!")
print("   Visit the next tutorial: '02_compartmental_modeling.ipynb'")

💾 Saving z-stack morphologies...
✅ Saved z-stack data files:
   - z_stack_data/cylinder.npz
   - z_stack_data/y_shaped.npz
   - z_stack_data/cylinder_with_hole.npz

📂 Loading z-stack data from file...
✅ Loaded cylinder z-stack:
   Shape: (53, 16, 16)
   Volume: 6664.0 µm³
   Neuron voxels: 3,332

🔍 Data integrity check:
   Arrays match: True
   Metadata matches: True

🎯 Z-stack format advantages:
   • Direct representation from imaging data (confocal, 2-photon, etc.)
   • Easy to work with complex/irregular morphologies
   • Natural fit for z-axis slicing algorithms
   • Preserves fine details and topology
   • Can represent any 3D shape accurately


## Next Steps with Z-stack Morphologies

Now that you understand GenCoMo's z-stack workflow, you can:

1. **Load imaging data**: Import confocal/two-photon reconstructions directly as z-stacks
2. **Build compartmental models**: Convert z-stack voxels to simulation compartments  
3. **Analyze morphology datasets**: Batch process multiple z-stack morphologies
4. **Integrate simulations**: Connect z-stack models to NEURON, Brian, or custom solvers

The z-stack format provides the most direct path from experimental data to computational models!

## Additional Resources

### Z-stack Format Documentation
- **File format**: `.npz` compressed NumPy arrays with metadata
- **Coordinate system**: (z, y, x) matching imaging conventions
- **Data type**: Boolean arrays (1=inside neuron, 0=outside)
- **Metadata**: Resolution, units, provenance information

### GenCoMo API Reference
- `create_*_zstack()` functions for test morphologies
- `analyze_zstack_properties()` for morphometric analysis  
- `visualize_zstack_3d()` for interactive visualization
- `save/load_zstack_data()` for file operations
- Mesh conversion utilities for legacy compatibility

### Integration Examples
- Loading imaging data from various formats
- Converting to compartmental simulation models
- Morphology analysis and classification workflows
- Multi-scale modeling approaches

In [ ]:
# Z-stack format resources and community
print("? GenCoMo Z-stack Resources")
print("=" * 40)
print()
print("🔗 Documentation:")
print("   • GenCoMo API docs: github.com/your-org/gencomo")
print("   • Z-stack format specification")
print("   • Imaging data integration guide")
print("   • Compartmental modeling tutorials")
print()
print("🧪 Example datasets:")
print("   • Test z-stack morphologies")
print("   • Reconstructed neuron samples")
print("   • Imaging pipeline outputs")
print()
print("🤝 Community:")
print("   • Share z-stack morphology datasets")
print("   • Contribute imaging data loaders")
print("   • Develop analysis workflows")
print("   • Integrate with simulation tools")
print()
print("🎯 Happy modeling with GenCoMo z-stacks! 🧠✨")

🔧 Step 1: Mesh Processing
✅ Loaded mesh with 802 vertices and 1600 faces

🔧 Preprocessing mesh...
  ✅ Centered mesh
  ✅ Aligned with z-axis

📊 Mesh Properties:
  Volume: 7653.67 µm³
  Surface area: 3274.52 µm²
  Is watertight: True
  Z-range: -50.0 to 50.0 µm


---

**🎉 Congratulations!** You've completed the GenCoMo introduction tutorial and learned the z-stack workflow for neuronal morphology analysis. 

**Key takeaways:**
- Z-stacks are GenCoMo's primary format for direct imaging integration
- Volume rendering provides intuitive 3D visualization
- Rich morphometric analysis supports research workflows  
- Efficient I/O enables data sharing and reproducibility
- Conversion utilities provide legacy format compatibility

**Ready for the next level?** Check out the compartmental modeling tutorial to convert your z-stack morphologies into simulation models!

---